### ISSUE TITLE
rework repo and add snakemake template info

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/reference-container#7]
copy the relevant parts of the snakemake template repo into this one (license, init script etc.) and make sure that the reference container repo looks and feels like it were created on the basis of the snakemake template.

**Comment by svenwillger** [comment]
All relevant parts and modifications have been made to the script so that it looks like the reference-container workflow was written on the basis of the template workflow.
I deleted the folder that contained the refcon_load.smk since this is now part of /rules/commons 
A quick test that the code is still functional as expected.

The commit message is "added files and code to resolve issue #7"

**Comment by ptrebert** [comment]
it's unclear where the info has been updated - I don't see a new branch?!

**Comment by ptrebert** [comment]
I see now that the info has been added to the `issue_T2T` branch; not a clean way.

One more point (the re-opener): the README is obviously outdated now, please update that to make it compatible with the usage of the snakemake template

**Comment by svenwillger** [comment]
Sorry, I saw the `ìssue_T2T` branch when I wanted to make a new one and assumed you specifically created that branch to work on the created issues and therefore used it.
I will also update the README

**Comment by svenwillger** [comment]
I reset the branch `ìssue_T2T` back to where is was and also reset the branch `dev` one step back and included all changes to resolve both issues #5 and #7 (issue #5 only added one sentence to the `functions.smk` module) in a single commit. The new commit also includes a modified README.
The commit comment is "updates to resolve issues #5 and #7"
